### ISSUE TITLE
RCM not work， shows BISKEY DUMP FAILED

### ISSUE THREAD

**Issue by Sorata** [StarDustCFW/Haku33#10]
With https://github.com/StarDustCFW/Haku33/blob/master/romfs/Haku33.te

TegraRcmSmash run Haku33_payload.bin:

t shows:
An error occured:

Function: dump_biskey
Errcode:57
Dese: BISKEY DUMP FAILED

Press any button to return.

**Comment by Kronos2308** [comment]
strange 
are your boot0/1 ok

**Comment by Kronos2308** [comment]
use the latest [tegra explorer](https://github.com/suchmememanyskill/TegraExplorer/releases) to open the script

**Comment by Sorata** [comment]
Yes,  You mean the boot0/1 in the emunand? I have boot0.bin and boot1.bin in /sxos/emunand.
But the script is used for the real system, not the emusystem, right?
The real system and emusystem both work well.

Thank you for your reply, let me try it.

**Comment by Sorata** [comment]
> 
> 
> use the latest [tegra explorer](https://github.com/suchmememanyskill/TegraExplorer/releases) to open the script

Aha, I run TegraExplorer.bin, it directly outputs:
An error occured:

Function: dump_biskey
Errcode:57
Dese: BISKEY DUMP FAILED

Press any button to return.

- -It looks like not your script's problem. strange……

**Comment by Kronos2308** [comment]
10.2.0 firm ?

**Comment by Kronos2308** [comment]
can you explore the system partition with tegra explorer

**Comment by Kronos2308** [comment]
if not work then boot up your sysnand whit cfw and use https://github.com/StarDustCFW/Haku33/releases/tag/2.9
that  version of haku33
if your nand have a brick haku33 is not gointo solve any

**Comment by Kronos2308** [comment]
and reemember to make abackup before do anything

**Comment by Sorata** [comment]
My real system's version is 9.0.0.

I can run tegra explorer by TegraRcmSmash in RCM. It shows the same error:

An error occured:

Function: dump_biskey
Errcode:57
Dese: BISKEY DUMP FAILED

Press any button to return.

Maybe my real system version too low or it's the  tegra explorer's problem.
Not a big problem, I just try your new way to play. Just for fun.

Yeah, your old version:2.9 is more powerful, because it work for the sx core device.

Thank you for your reply and advices, have a nice day^_^

**Comment by Kronos2308** [comment]
more unstable also

**Comment by Sorata** [comment]
> 
> 
> more unstable also

You make big help for the people who forget to backup nand. I write blog to introduce how to use Haku33.
And a lot of people have got your help. Good job!
