### ISSUE TITLE
Hi friend，can you rebuild a 2.9 version which support 11.0.0 OS？

### ISSUE THREAD

**Issue by Sorata** [StarDustCFW/Haku33#12]
Only 2.9 can worked in SX Core, it looks like reset OK, but restart not found red Nintendo.
![20201208141633](https://user-images.githubusercontent.com/2240909/101447359-0b0d5980-3960-11eb-93fd-a1c191946814.jpg)

**Comment by Kronos2308** [comment]
I believe sxos has in the main menu the option to run any payload 
You can use the rcm version in the boot menu 
If not then just 

Disable stealth mode and ftp in sxos before run haku33 2.9

Because 3.x and up are using a payload in rcm to made the clean

**Comment by Sorata** [comment]
Thank you for your reply.
The latest news, version 2.9 is still valid, the memory card format must be FAT32.
The format of the memory card was omitted during the test,  sorry for the wrong issue feedback. 
I'm sorry~ Apologize agai^_^
