### ISSUE TITLE
Is 12.0.1 firmware supported?

### ISSUE THREAD

**Issue by ress1819** [StarDustCFW/Haku33#13]
Thank you for your contributions, and recent 3.3 release supporting up to 12.0.0. Sorry if my issue is silly but I am a newbie and have already googled with no avail. I accidentally updated my firmware from 12.0.0 before changing my mind on having my CFW on sysNAND. Will the latest 3.3 release work on 12.0.1 firmware?

**Comment by Kronos2308** [comment]
Has long has the pkg1 not change should work

**Comment by Kronos2308** [comment]
The worse can happen is that not work
