### ISSUE TITLE
Error 13.0.0 keydump failed

### ISSUE THREAD

**Issue by sebastienpuylaurent** [StarDustCFW/Haku33#15]
Hi ! 

Err : 21
Line : 303
File : source/main.c
Desc : Keydump failed 

Once I star the cleaning I get this error, please can I have help ? ^^' And thanks for the work btw, I really want to use this.

**Comment by Kronos2308** [comment]
use tegra explorer System wipe

**Comment by Kronos2308** [comment]
Fixed on 4.2
