### ISSUE TITLE
Asking about Hot to use in Hekate More configs.

### ISSUE THREAD

**Issue by Sorata** [StarDustCFW/Haku33#16]
Hi, can you give me an example about how to use Hekate in Hekate More configs?

I found the config ini in romfs/ini, but I can not find the Hekate.bin. I see the release only hava nro.

I tryied rename haku33.nro to haku33.bin, but where I launch it through More configs, device return black screen
 I think there must be some reasons I don't know.

Could you please give me a more detailed explanation about how mariko device use through  More configs?

**Comment by Kronos2308** [comment]
Loading hekate by yournown or just using StardustCfwpack
haku33 is not meent to be usted on mariko since thet cant reboot to payload so thet way infound is to usé that or just load tetra Explorer
