### ISSUE TITLE
Ver 4.3 Wipe sysmmc show error after show Green Done.

### ISSUE THREAD

**Issue by Sorata** [StarDustCFW/Haku33#18]
![Screenshot_0314dfd4](https://user-images.githubusercontent.com/2240909/134771389-f757a141-3db1-46e2-86f0-484fd75393dd.jpg)

It looks like the line:`color("GREEN")` should change to  `color(0x00FF00)`
Maybe println need to replace p too?

**Comment by Kronos2308** [comment]
you are right
https://github.com/StarDustCFW/Haku33/tree/4.4
