### ISSUE TITLE
4.4 still "keydump failed"

### ISSUE THREAD

**Issue by mike2036** [StarDustCFW/Haku33#19]
console: SwitchLite-mariko(chip cracked), 13.0.0s
haku33 version: 4.4

Tegra explorer 4.0.1

"
Err   : 21
Line : 303
File  : source/main.c
Desc: Keydump failed

Press A to continue
"

Pressed power btn to continue, it says "[WARN] Keys required. Make sure you're on the latest version of TegraExplorer!"
then power btn again, slided to systemWipe.te, press power, it says "[WARN] Keys required. Make sure you're on the latest version of TegraExplorer!"

Please help, thanks for your time! 
Truely appreaciate it!

**Comment by Kronos2308** [comment]
@Michael2049  try to make adump or your biskeys with lock pick becouse i not  hat mariko keys

**Comment by Kronos2308** [comment]
try [4.5](https://github.com/StarDustCFW/Haku33/releases/download/4.5/Haku33.nro)

**Comment by mike2036** [comment]
thanks a lot!
