### ISSUE TITLE
Would you consider adding support for 13.2.1?

### ISSUE THREAD

**Issue by jwguo321** [StarDustCFW/Haku33#20]

**Comment by Kronos2308** [comment]
Haku33 yes y have to add a exeption for tje new firmware

**Comment by Kronos2308** [comment]
try [4.6](https://github.com/StarDustCFW/Haku33/releases/tag/4.6)

**Comment by jwguo321** [comment]
> try [4.6](https://github.com/StarDustCFW/Haku33/releases/tag/4.6)

all right. Thank you very much
