### ISSUE TITLE
Black screen on mariko

### ISSUE THREAD

**Issue by rustark** [StarDustCFW/Haku33#21]
After starting the program (v4.5 on mariko) from hekate, the black screen on switch oled (FW 13.1.0)

**Comment by Kronos2308** [comment]
tegra explorer not work on mariko oled

**Comment by Ic-any** [comment]
Yes, I have tried to use Haku33 on OLED machine. It works fine but I can't see it, but just press the key. I have washed it more than 10 times and I am familiar with what key I pressed.

**Comment by Kronos2308** [comment]
> Yes, I have tried to use Haku33 on OLED machine. It works fine but I can't see it, but just press the key. I have washed it more than 10 times and I am familiar with what key I pressed.

yes on [5.2](https://github.com/StarDustCFW/Haku33/releases/tag/5.2) you jus neet to press power once to clean and power off

**Comment by EnriqueSchz** [comment]
apply the clean with Haku 5.2 in version 5.2 on my nintendo switch OLED with firmware 16.0, the console turned off and when trying to turn on the HWFly it shows a green light, however the console does not turn on. I hope you can help me

**Comment by Kronos2308** [comment]
mmm replace the payload.bin
