### ISSUE TITLE
Missing 16.0.0 Support?

### ISSUE THREAD

**Issue by SamHGA** [StarDustCFW/Haku33#22]
Tried using Haku33 on HOS 16.0.0 through title override with no success, not sure if it has to do with Haku33 or something else though.
Had to boot into stock HOS and initialize the console from there.

On Atmosphere 1.5.0, hekate 6.0.2.

**Comment by Kronos2308** [comment]
https://github.com/StarDustCFW/Haku33/releases/tag/5.2
