### ISSUE TITLE
Black Screen Nintendo Switch OLED,

### ISSUE THREAD

**Issue by EnriqueSchz** [StarDustCFW/Haku33#23]
I applied the clean, but now my Switch does not turn on

**Comment by Kronos2308** [comment]
try pulse power 3 times and if not boot pulse power 15s and then try power on again
also 
check if payload.bin exist on the sd card

**Comment by EnriqueSchz** [comment]
do you know Spanish? maybe it's easier

**Comment by Kronos2308** [comment]
si
claro

**Comment by EnriqueSchz** [comment]
comentare el problema mas completo, mi switch tiene instalado el HWFly, utilice Hakku desde la Sysnand, la consola se apago con el LED del control encendido, pero al prenderla, el chip se pone morado, luego verde, se supone que deberia dar imagen de HEKATE, pero no la arroja y anteriormente ya la habia arrojado, voy a intentar cambar el Payload.bin, tienes alguno en especifico?

**Comment by Kronos2308** [comment]
pues lo que pasa es que estaba probando justo eso pero paraece que corrompio el payload.bin

**Comment by EnriqueSchz** [comment]
orita donde estoy no tengo como conectar la memoria SD a la computadora, crees que al formatearse la consola por usar hakku, tambien haya formateado la SD? ya que quite la SD y la prendi y se arroja la imagen del cohete donde dice NO SD

**Comment by Kronos2308** [comment]
solo se corrompio ese fichero que es el q se usa para arranacar pero puedes ponerlo de nuevo
