### ISSUE TITLE
nintendo switch lite，black screen after clean

### ISSUE THREAD

**Issue by Gygert** [StarDustCFW/Haku33#24]
atmosphere SYS 16.0 AMS 15.0

**Comment by Kronos2308** [comment]
Try to dump the keys first with lock pick rcm

**Comment by Kronos2308** [comment]
And seems like Mariko models are not supported by tegra explorer so you may have to use haku33 2.4

**Comment by Gygert** [comment]
ok,i found other's payload.bin to replace mine,it worked,and i in real system and it looks like system is initialized？Now i dare not to do more，should i continue to clean？

**Comment by Kronos2308** [comment]
With Mariko there is the problem of compatibility so I made a work around to solve that ,but it seems like work else d'not restore the payload.bin after finish
Y may solve that in future releases
