### ISSUE TITLE
my switch won't power on

### ISSUE THREAD

**Issue by sprigotori** [StarDustCFW/Haku33#26]
I wiped my switch using haku33 and got a black screen with my home button glowing but it doesn't seem to power on anymore. please help me
![WIN_20230531_21_21_50_Pro](https://github.com/StarDustCFW/Haku33/assets/135168278/0cb39bdb-5433-4f0c-b5f6-7f294451074a)

**Comment by Kronos2308** [comment]
Pulse power 12s

**Comment by DonutMaker77** [comment]
I'm facing the same issue, it does shows NO SD when SD card is ejected.

**Comment by Kronos2308** [comment]
Because your switch have a chip

**Comment by DonutMaker77** [comment]
> Because your switch have a chip

Huh?

Anyway managed to turn it back on again.

**Comment by sprigotori** [comment]
I was able to fix it I had to turn of RCM mode and just tried agian. (if your switch has a black screen try to plug it in your pc to start it through the program.)
