### ISSUE TITLE
Updating to 17.0.0 soft-bricks the consoles wiped out using Haku33

### ISSUE THREAD

**Issue by wf-** [StarDustCFW/Haku33#27]
Explained thoroughly by [SciresM](https://github.com/SciresM), so I'll just link to [their writeup](https://gist.github.com/SciresM/2ddb708c812ed585c4d99f54e25205ff).

Workaround: Booting to Atmosphere >=1.6.1 will unbrick the console.

**Comment by Kronos2308** [comment]
Haku has no support to 17.0.0 jet

**Comment by javiermv4** [comment]
If you use Haku33 before updating to 17.0.0, if you then update to 17.0.0 it also soft-bricks the console. I mean, this soft-brick is not a result of using Haku33 directly in 17.0.0.

**Comment by Kronos2308** [comment]
Nintendo in 17.0.0 and a check to see if people has ben rebuild system partition and the soft brick the console for somo unknown reason (I will investigate)
To unbrik you just have to run atmosphere once

**Comment by Kronos2308** [comment]
I will see if I can fix that for good

**Comment by Kronos2308** [comment]
the release [5.7](https://github.com/StarDustCFW/Haku33/releases/tag/5.7) has fix the issue but the damage is arredy done so, need to run Atmosphere on the sysnand or emunand to fix the problem

**Comment by ghost** [comment]
@Kronos2308 Previous releases had English text, but the one you linked to is in Spanish. Did you write it in Spanish or did Github somehow mess up my language settings?

**Comment by Kronos2308** [comment]
i write in spanish is my main language

**Comment by Kronos2308** [comment]
done is in english now

**Comment by javiermv4** [comment]
No sabía que hablabas español jeje. Acabo de arreglar el problema :), gracias!
