### ISSUE TITLE
17.0.1 Black screen after OLED uses haku33

### ISSUE THREAD

**Issue by Ic-any** [StarDustCFW/Haku33#31]
The problem found so far is that after the whitewashing is completed, re-enter the system. After the real cracking and the genuine system enter, the Nintendo icon is lit up, and the black screen will not respond after a while.
Use lockpink-rcm to extract the system firmware, which cannot be extracted. The machine seems to have turned into bricks.
![IMG_8750](https://github.com/StarDustCFW/Haku33/assets/92638461/2601ad90-ecb4-4737-bca7-5b71bc9124d7)
![IMG_8749](https://github.com/StarDustCFW/Haku33/assets/92638461/2f402184-5148-47b5-a6f6-f48541025b68)
![IMG_8748](https://github.com/StarDustCFW/Haku33/assets/92638461/89825210-c351-4408-9f06-65452c1623b7)

**Comment by Kronos2308** [comment]
This issue has nothing to be with Haku33.
You should probably need to check the chip data0 connection and check the installation
 Or is probably a SD issue try another SD off good quality first
