### ISSUE TITLE
Problemas en ReiNX tras hacer el hard-reset

### ISSUE THREAD

**Issue by t33st33r** [StarDustCFW/Haku33#4]
Hago todo como indica pero una vez termina y se apaga la pantalla procedo a encender normalmente (como si estuviera virgen) pero de nuevo vuelve a arrancar ReiNX y me vuelve a hackear la sysNAND.

Imagino que no sea problema del homebrew pero estoy estancado en este punto y no se a donde mas acudir.

Ayuda por favor. Gracias.

PD: Para futuras releases... ¿podrias hacer que sea opcional el borrado del .nro? En caso de que el homebrew pueda leer el nombre de su propio .nro se me ocurre que segun el nombre que tenga pueda permanecer una vez hecho su trabajo. Si no,,, 2 .nro distintos... uno que se borre y otro que no. ¿El motivo? cada prueba que hago tengo que sacar y cambiar de sitio la tarjeta para volver a meter el homebrew.

**Comment by t33st33r** [comment]
Ya lo he solucionado sacando la SD antes del nuevo inicio y arrancando en RCM el lockpick. De ahi mando apagar y el siguiente inicio ya esta OK.
Pero igual estaria bien lo de conservar (opcionalmente) el haku33 despues de su uso.

**Comment by Kronos2308** [comment]
Lo que pasa es que es opcional solo que no sabías como funciona

Al terminar la limpieza la consola se reinisa al un payload que termina de ajustar la sd 
(Cosas que no se pueden tocar con el sistema prendido)

Luego permanece a la espera una especie de sleep 
En este sleep 
pulsar power carga un fichero payload.bin de la raiz
Pulsar Vol+   power juntos pone la consola en rcm
Y mantener power 5s la apaga por completo solo si no existe un payload.bin que cargar

En tu caso solo tenias que sacar la sd una vez completar y pulsar power 5s eso abria apagado la consola 


Lo tengo asi par quienes quieran cargar el menu de hekate y desabilitar autorcm o directamente arrancar ofw desde hekat o el menu de StarDustcfwpack

**Comment by t33st33r** [comment]
"Al terminar la limpieza la consola se reinicia a un payload que termina de ajustar la sd"

¿Es la SD la que necesita ese ultimo retoque o es la NAND? De ser la SD en mi caso no creo que importe (mi intencion es borrar todo en la SD y empezar de cero).

En caso de que ese ultimo paso tuviese que tocar algo en la NAND... ¿realmente tengo la NAND como si el proceso hubiese ocurrido sin obstaculos?

**Comment by Kronos2308** [comment]
En principio el payload es señal de luz verde o sea que termino sin contratiempos

De la sd solo renombra la carpeta Nintendo para evitar conflicto y borra el haku33 de la raiz 

Ya te dije tu caso es especial ya que tenias el  payload.bin de reinx en la raiz y eso te hacia iniciar reinx solo tenias que sacar la sd formatearla y apagar la consola y en caso de que tengas autorcm y no lo quieras. Con desactivar desde hekate tienes

**Comment by t33st33r** [comment]
OK. Listo entonces. Muchas gracias.
