### ISSUE TITLE
Need haku33 or not ?

### ISSUE THREAD

**Issue by deejay87** [StarDustCFW/Haku33#5]
Hello
do we really need haku33 or just an hard reset is good ? lot of people are just use hard reset et don't get ban
Thanks

**Comment by Kronos2308** [comment]
Well a hard reset from the system menu 
D'not delete all 
Haku Force the delete of all saves from the system
Is the same that delete with hack disk mount 

I know of some people that get ban for only make a reset from the console

Normally the reset delete personal information not system logs
