### ISSUE TITLE
Question - OFW isn't restored to factory - is the system clean?

### ISSUE THREAD

**Issue by at453383** [StarDustCFW/Haku33#7]
Hello!
First of all, thank you for the awesome tool.

I used it to factory reset the system, however, the OFW stays in 9.2 (which I manually updated in the past, using Choidujour).

Would you think this is as clean as I can get the system to - can I go back online even though the OFW wasn't updated through Nintendo's servers?

(For some reason, I thought I had done a proper NAND backup, turns out I just created a small backup of something else so I cannot restore to my original NAND anymore).

Thank you kindly for your time

**Comment by Kronos2308** [comment]
This is not a issue
Remember is Factory reset 
Haku33 is goin to clean not to update your system 

Use the discord link for support
